### PR TITLE
Ex00

### PR DESCRIPTION
**Pull request by Andrehoi**
Talked to Yngve about last weeks assignment. He saw i tried to merge with the wrong repository and said this pull request is okay.

In this pull request you can find changes requested in Ex00 and the corrected scripts from Ex01.

Sincerely
Andreas Sandvik Høimyr

### CODE REVIEW

**Review by ahmedalbuni — COMMENTED** [review]
Please avoid using Norwegian characters it might cause some issues
I will approve this pull request after correcting ex01

**Comment by Andrehoi** [comment]
Hei, ex01 is also in this pull request as mentioned in the pull request comment.

Hope you can approve it so i can begin working on ex02.


________________________________
Fra: ahmedalbuni <notifications@github.com>
Sendt: tirsdag 17. september 2019 12:07
Til: Andrehoi/INF200-2019-Exersices <INF200-2019-Exersices@noreply.github.com>
Kopi: Andreas Sandvik Høimyr <andreas.sandvik.hoimyr@nmbu.no>; Author <author@noreply.github.com>
Emne: Re: [Andrehoi/INF200-2019-Exersices] Ex00 (#1)


@ahmedalbuni commented on this pull request.

Please avoid using Norwegian characters it might cause some issues
I will approve this pull request after correcting ex01

**Comment by Andrehoi** [comment]
I also discovered I made a mistake on one of the exercises for ex01. I have corrected it on my computer. Should i update that task when turning in Ex02?

**Review by ahmedalbuni — CHANGES_REQUESTED** [review]
pep8 violations, no new line at the end of comp_by_loop.py and tidy_code.py

**Comment by Andrehoi** [comment]
Updated the requested files in the branch EX00. However i am uncertain if i have to create a new pull request or if this request automatically is updated?

**Review by ahmedalbuni — APPROVED** [review]
Approved, for modifying the grade, I need to check with Yngve

**Pull request merged**
